#! /bin/bash

if [ ! -e 1dwd_rec.maps.fld ]; then
	bash ../dock_rigidlig/make_rec_maps
fi

autodock4 -p 1dwd_lig_1dwd_flexres_1dwd_rigid.dpf \
  -l 1dwd_lig_1dwd_flexres_1dwd_rigid.dlg

# autodock4 -p 1dwd_lig_1dwd_flexres_1dwd_rigid_long.dpf -l 1dwd_lig_1dwd_flexres_1dwd_rigid_long.dlg


