#! /bin/bash

if [ ! -e 1dwd_rec.maps.fld ]; then
	bash ../dock_rigidlig/make_rec_maps
fi

autodock4 -p 1dwd_local_only.dpf -l 1dwd_local_only.dlg

# autodock4 -p 1dwd_local_only_long.dpf -l 1dwd_local_only_long.dlg

autodock4 -p 1dwd_local_only_best.dpf -l 1dwd_local_only_best.dlg

# autodock4 -p 1dwd_local_only_best_long.dpf -l 1dwd_local_only_best_long.dlg
