bwa:
  dindex: 'False'
  params: +R "@RG\tID:RG1\tSM:RGSN1"  
  rindex: 'False'
dataset:
  index: GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
  input: /input/
  outfile: short.se.sam
  output: /out/
  read1: HG001.novaseq.pcr-free.30x.R1.fastq.gz
  read2: HG001.novaseq.pcr-free.30x.R2.fastq.gz
  read_type: short
  refdir: /refdir/
  tempdir:  ""
fqprocess:
  bam_size: '5'
  barcode_orientation: FIRST_BP_RC
  output_format: FASTQ
  prefix: multiome-practice-may15_arcgtf
  read3: ''
  read_structure: 16C
  readi1: ''
  sample_id: ''
  suffix: trimmed_adapters.fastq.gz
  whitelist: whitelist.txt
mm2:
  params: ' -ax map-hifi '
